### ISSUE TITLE
Tiling/halo bug in AG

### ISSUE THREAD

**Issue by AndyHoggANU** [AndyHoggANU/anu-tub#11]
I'm now running some new cases with the revised AG scheme. There are a few issues to deal with here -- and they may overlap. But I'll list them all as separate issues for now. The first one is shown in the picture below. This is cell thickness at some depth:

![Screenshot 2024-06-09 at 2 15 34 PM](https://github.com/AndyHoggANU/anu-tub/assets/26753100/622830d1-e028-4f61-961b-b393063e77ab)

You can see six clear meridional lines, about 4 grid points wide ... i.e., exactly where the halos are! I think this indicates a meridional halo bug, right @angus-g??

**Comment by angus-g** [comment]
Yeah, I'd agree with that. Possibly a result of the latest smoothing addition!

**Comment by angus-g** [comment]
I've just pushed https://github.com/angus-g/MOM6/commit/754496e219c6ec7e77c7d1a03504a0d97c6753e8 which should hopefully deal with this and #13 (maybe also #12 if it's somehow gaining mass through bogus interface movement...). It's available at `/g/data/x77/ahg157/exes/MOM6/AG-774f4402`.

I don't think this is the "best" way to fix the issue: I've essentially cut off the filtering stencil at the halo, so we don't have to push them out even further for the calculation. I suppose it would be possible to do a halo exchange of the local `dz_s` fields before the stencil, so that we have the full halo available, but that would require some restructuring of the loops.

Because the smoothing doesn't see across the halo, I suppose this won't reproduce properly across layouts, but I wonder if we'll still see a discontinuity in this case?

**Comment by AndyHoggANU** [comment]
OK, will test it out.

**Comment by AndyHoggANU** [comment]
Think this is fixed with the above update.

<img width="730" alt="Screenshot 2024-06-15 at 10 33 26 AM" src="https://github.com/AndyHoggANU/anu-tub/assets/26753100/8d7b914f-a1d2-4e5a-bae0-cea72005a973">
