### ISSUE TITLE
Comparison with OM4

### ISSUE THREAD

**Issue by AndyHoggANU** [AndyHoggANU/anu-tub#3]
We should carefully crosschecked namelist parameters against OM4 (and panant?) case to confirm we are happy with these parameters.

**Comment by angus-g** [comment]
Here's a somewhat randomly-ordered list of parameters that differ from OM4. I've highlighted in bold the ones that I'd assume are responsible for the most significant differences between the two configurations. There are a lot of parameters dedicated to recovering a specific set of old answers, but I don't think we need to worry about them, because it was just from a numerics change that applies near roundoff, not a significant effect at all. I can provide the parameter documentation for anything that sounds interesting, however.

Parameter                         | anu-tub  | OM4
--------------------------------- | -------- | ------
**`THICKNESSDIFFUSE`**                | *False*  | *True*
`THICKNESSDIFFUSE_FIRST`          | *False*  | *True*
`DT_THERM`                        | 3600.0   | 7200.0
`INTERPOLATION_SCHEME`            | *PPM_H4* | *P1M_H2*
**`USE_MEKE`**                        | *False*  | *True*
**`CHANNEL_DRAG`**                    | *False*  | *True*
**`LAPLACIAN`**                       | *False*  | *True*
`THERMO_SPANS_COUPLING`           | *False*  | *True*
`DTBT_RESET_PERIOD`               | 3600.0   | 7200.0
`FRAZIL`                          | *False*  | *True*
`DO_GEOTHERMAL`                   | *False*  | *True*
`MIN_SALINITY`                    | 0.0      | 0.01
`USE_PSURF_IN_EOS`                | *True*   | *False*
`BAD_VAL_SSS_MAX`                 | 45.0     | 75.0
`BAD_VAL_SST_MAX`                 | 40.0     | 55.0
`BAD_VAL_SST_MIN`                 | -6.0     | -3.0
`USE_STORED_SLOPES`               | *False*  | *True*
`INTERNAL_WAVE_SPEED_BETTER_EST`  | *True*   | *False*
`AH`                              | 5.0E+09  | 0.0
`MIXEDLAYER_RESTRAT`              | *False*  | *True*
`USE_LEGACY_DIABATIC_DRIVER`      | *False*  | *True*
`KD_MIN_TR`                       | 2.0E-06  | 1.5E-06
`INT_TIDE_DISSIPATION`            | *False*  | *True*
`HENYEY_IGW_BACKGROUND`           | *False*  | *True*
`KD`                              | 2.0E-05  | 1.5E-05
`KDML`                            | 2.0E-05  | 1.5E-05
`KD_KAPPA_SHEAR_0`                | 2.0E-05  | 1.5E-05
`KD_TRUNC_KAPPA_SHEAR`            | 2.0E-07  | 1.5E-07
`PRESSURE_DEPENDENT_FRAZIL`       | *False*  | *True*
`VAR_PEN_SW`                      | *False*  | *True*
`EPBL_MLD_BISECTION`              | *False*  | *True*
`PEN_SW_ABSORB_MINTHICK`          | 1.0      | 0.001
`FLUXCONST`                       | 0.2      | 0.1667
`FLUXCONST_S`                     | 0.0      | -
`FLUXCONST_SALT`                  | -        | 0.1667
**Old answers** | |
`DEFAULT_2018_ANSWERS`            | *False*  | *True*
`SURFACE_2018_ANSWERS`            | *False*  | *True*
`REMAP_UV_USING_OLD_ALG`          | *False*  | *True*
`REMAPPING_2018_ANSWERS`          | *False*  | *True*
`SET_VISC_2018_ANSWERS`           | *False*  | *True*
`USE_GM_WORK_BUG`                 | *False*  | *True*
`HOR_VISC_2018_ANSWERS`           | *False*  | *True*
`VERT_FRICTION_2018_ANSWERS`      | *False*  | *True*
`BAROTROPIC_2018_ANSWERS`         | *False*  | *True*
`BT_USE_OLD_CORIOLIS_BRACKET_BUG` | *False*  | *True*
`SET_DIFF_2018_ANSWERS`           | *False*  | *True*
`KAPPA_SHEAR_ITER_BUG`            | *False*  | *True*
`KAPPA_SHEAR_ALL_LAYER_TKE_BUG`   | *False*  | *True*
`EPBL_2018_ANSWERS`               | *False*  | *True*
`OPTICS_2018_ANSWERS`             | *False*  | *True*

**Comment by AndyHoggANU** [comment]
just to note, i'm pretty happy with these parameter differences, so will close this for now.
